#!/bin/bash

echo "Five seconds to showtime!"
echo "To cancel press CTRL + C to cancel..."

#Pauses install just in case you want to cancel
sleep 5s
echo "================================================"
echo "================================================"
sudo apt update && sudo apt upgrade -y

echo "Let's install some apps."
sleep 5s

sudo apt remove --purge libreoffice* -y
sudo apt install htop -y
sudo apt install nala -y
sudo apt install neofetch -y
sudo apt install wget -y
sudo apt install steam -y
sudo apt install solaar -y
sudo apt install gh -y
sudo apt install lolcat -y
sudo apt install fastfetch -y
sudo apt install cups -y
sudo apt install ipmitool -y

#This is testing creation of folders that will be needed for fstab
sudo mkdir /media/steam
sudo mkdir /media/extra
sudo mkdir /media/steam-wd

#Installing TailScale
curl -fsSL https://pkgs.tailscale.com/stable/debian/sid.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
curl -fsSL https://pkgs.tailscale.com/stable/debian/sid.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
sudo apt-get update -y
sudo apt-get install tailscale -y
sudo tailscale up
sudo tailscale up --operator=$USER

#Installing Mullvad VPN
# Download the Mullvad signing key
sudo curl -fsSLo /usr/share/keyrings/mullvad-keyring.asc https://repository.mullvad.net/deb/mullvad-keyring.asc

# Add the Mullvad repository server to apt
echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable stable main" | sudo tee /etc/apt/sources.list.d/mullvad.list

# Install the package
sudo apt update
sudo apt install mullvad-vpn

#Installing flatpak repository and installing flatpak programs
flatpak install flathub org.fkoehler.KTailctl -y
flatpak install flathub com.vscodium.codium -y
flatpak install flathub dev.mariinkys.StarryDex -y
flatpak install flathub io.freetubeapp.FreeTube -y
flatpak install flathub org.signal.Signal -y
flatpak install flathub com.github.iwalton3.jellyfin-media-player -y
flatpak install flathub media.emby.EmbyTheater -y
flatpak install flathub org.gimp.GIMP -y
flatpak install flathub de.haeckerfelix.Shortwave -y
flatpak install flathub tech.feliciano.pocket-casts -y
flatpak install flathub com.obsproject.Studio -y
flatpak install flathub app.xemu.xemu -y
flatpak install flathub net.lutris.Lutris -y
flatpak install flathub com.usebottles.bottles -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub org.remmina.Remmina -y
flatpak install flathub io.gitlab.librewolf-community -y
flatpak install flathub com.github.unrud.VideoDownloader -y
flatpak install flathub md.obsidian.Obsidian -y
flatpak install flathub org.deluge_torrent.deluge -y
flatpak install flathub org.freac.freac -y
flatpak install flathub net.freerct.FreeRCT -y
flatpak install flathub org.libreoffice.LibreOffice -y
flatpak install flathub com.moonlight_stream.Moonlight -y
flatpak install flathub org.gnome.Boxes -y
flatpak install flathub io.github.giantpinkrobots.flatsweep -y
flatpak install flathub org.gnome.World.PikaBackup -y
flatpak install flathub com.spotify.Client -y
flatpak install flathub org.mozilla.Thunderbird -y
flatpak install flathub io.github.tobagin.digger -y



Exit
echo "================================================"
echo "================================================"

cat << "EOF"

Script written by:
 ______   _______     ________  ____  _____  ______        _       ____  _____
|_   _ \ |_   __ \   |_   __  ||_   \|_   _||_   _ `.     / \     |_   \|_   _|
  | |_) |  | |__) |    | |_ \_|  |   \ | |    | | `. \   / _ \      |   \ | |
  |  __'.  |  __ /     |  _| _   | |\ \| |    | |  | |  / ___ \     | |\ \| |
 _| |__) |_| |  \ \_  _| |__/ | _| |_\   |_  _| |_.' /_/ /   \ \_  _| |_\   |_
|_______/|____| |___||________||_____|\____||______.'|____| |____||_____|\____|
